[package]
name = "wasm-reloc-analysis"
version = "0.1.0"
authors = ["Navidem <navid.emamdoost@gmail.com>"]

[dependencies]
parity-wasm = "0.31.0"
petgraph = "0.4.12"
wasmparser = "0.17.0"
byteorder = "1.2.3"
